version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ./scamazon/requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 ./scamazon/manage.py test ./scamazon/store
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - store_test_results:
          path: test-results/