# Generated by Django 4.2.10 on 2024-03-17 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_description_alter_book_pages_alter_book_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingID', models.CharField(max_length=13)),
                ('quantity', models.IntegerField(default=1)),
                ('userID', models.CharField(max_length=20)),
                ('isbn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('userID', models.CharField(max_length=20)),
                ('listingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.listing')),
            ],
        ),
    ]
