# Generated by Django 4.2.10 on 2024-03-20 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_book_quantity_listing_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
