# Generated by Django 4.2.10 on 2024-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_image_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oldListingId',
            field=models.IntegerField(default=0),
        ),
    ]
