# Generated by Django 4.2.10 on 2024-04-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_oldlistingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oldListingImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.image'),
        ),
    ]
